In [1]:
import numpy as np

## 11. Create a 3x3 identity matrix (★☆☆)

In [2]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 12. Create a 3x3x3 array with random values (★☆☆)

In [3]:
v = np.random.random((3, 3, 3))
print(v)

[[[0.41911346 0.41346429 0.12694507]
  [0.95013385 0.5891857  0.98519196]
  [0.32399227 0.76427644 0.05988193]]

 [[0.57148222 0.85497999 0.87801879]
  [0.92863675 0.21606335 0.8148309 ]
  [0.65593568 0.27555585 0.6818423 ]]

 [[0.77180301 0.20359882 0.07512473]
  [0.11286211 0.05784705 0.05641033]
  [0.83273011 0.09385328 0.99560078]]]


## 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [4]:
v = np.random.random((10, 10))
print(v)
print(v.min())
print(v.max())

[[0.32329863 0.47521739 0.8366163  0.64502315 0.73594652 0.05877986
  0.2405844  0.94541083 0.91287162 0.63743269]
 [0.10990732 0.09788515 0.19037289 0.62962795 0.01327656 0.43463371
  0.7416621  0.7866198  0.75505861 0.29431809]
 [0.50258905 0.11519587 0.01480214 0.81561967 0.99496579 0.18950866
  0.01412284 0.63382513 0.45852623 0.85889024]
 [0.11835181 0.34378717 0.39592632 0.3569367  0.48668981 0.87209919
  0.1647851  0.38268362 0.13522743 0.6845483 ]
 [0.940066   0.09142212 0.49987469 0.8326881  0.33573892 0.50958228
  0.4561838  0.51538563 0.54760727 0.48682712]
 [0.39306188 0.00916893 0.91493491 0.60823885 0.04946887 0.44969721
  0.72909349 0.93976519 0.02982945 0.58076855]
 [0.15218274 0.91872906 0.45324696 0.43889722 0.72979656 0.60784368
  0.72588527 0.77669773 0.20820497 0.01429434]
 [0.42248711 0.70010061 0.51684023 0.10826381 0.52100548 0.69703119
  0.40387824 0.00699743 0.227939   0.9498056 ]
 [0.02683887 0.18964929 0.80099809 0.58293396 0.37389117 0.30630551
  0.23509878

## 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [5]:
v = np.random.random(30)
print(v.mean())

0.48432487915904127


## 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [6]:
v = np.ones((4, 4))
print(v)
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


## 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [7]:
v = np.ones((4, 4))
size = v.shape[0]
col = np.zeros((size, 1))
v = np.hstack([col, v, col])
row = np.zeros(size+2)
v = np.vstack([row, v, row])
print(v)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
v = np.ones((4, 4))
v = np.pad(v, pad_width=1, mode='constant', constant_values=0)
print(v)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## 17. What is the result of the following expression? (★☆☆)

In [9]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


## 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
v = np.diag(1+np.arange(4), k=-1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [11]:
v = np.zeros((8, 8))
v[1::2, ::2] = 1
v[::2, 1::2] = 1
print(v)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [12]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)
