## 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
import numpy as np

In [4]:
mat = np.array([[0, 1], [1, 0]])
v = np.tile(mat, [4, 4])
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
# np.tile は配列をタイル上に並べてくれる
mat = np.array([1, 2])
v = np.tile(mat, 2)
print(v)

[1 2 1 2]


In [6]:
mat = np.array([1, 2])
v = np.tile(mat, [2, 2])
print(v)

[[1 2 1 2]
 [1 2 1 2]]


## 22. Normalize a 5x5 random matrix (★☆☆)

In [7]:
v = np.random.random((5, 5))
max, min = v.max(), v.min()
v = (v - min) / (max - min)
print(v)

[[ 0.96186302  0.50104402  0.52241341  0.25429708  0.06453218]
 [ 0.21963605  0.72029253  0.64628718  0.24716534  0.51009711]
 [ 0.16219552  0.86179802  0.6560239   0.36792635  0.43390016]
 [ 0.88562273  0.73773724  0.35608773  1.          0.52806011]
 [ 0.67137815  0.38049717  0.90613216  0.          0.09309362]]


## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [8]:
color_dt = np.dtype([
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)
])

## 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
a = np.arange(15).reshape(5, 3)
b = np.arange(6).reshape(3, 2)
v = np.dot(a, b)
print(v)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [10]:
v = a @ b
print(v)

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


## 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
v = np.arange(10)
v[(v >= 3) & (v <= 8)] *= -1
print(v)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


## 26. What is the output of the following script? (★☆☆)

In [13]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


## 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [14]:
Z = np.arange(3)
print(Z**Z)

[1 1 4]


In [15]:
print(2 << Z >> 2)

[0 1 2]


In [16]:
print(Z <- Z)

[False False False]


In [17]:
print(1j*Z)

[ 0.+0.j  0.+1.j  0.+2.j]


In [18]:
print(Z/1/1)

[ 0.  1.  2.]


In [19]:
print(Z<Z>Z)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28. What are the result of the following expressions?

In [20]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -9.22337204e+18]


/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/srv/conda/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


## 29. How to round away from zero a float array ? (★☆☆)

In [21]:
v = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(v)), v))

[ -1.  -2.  -3.  -3.   5.   6.   7. -10.   2.  -3.]


## 30. How to find common values between two arrays? (★☆☆)

In [23]:
v1 = np.random.randint(0, 10, 10)
v2 = np.random.randint(0, 10, 10)
print(v1)
print(v2)

[8 8 1 7 8 0 1 3 7 5]
[0 7 4 9 8 7 7 8 9 8]


In [ ]:
print(np.intersect1d(v1, v2))