## 1. Import the numpy package under the name np (★☆☆)


In [0]:
import numpy as np

## 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.14.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


## 3. Create a null vector of size 10 (★☆☆)

In [3]:
v = np.zeros(10)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4. How to find the memory size of any array (★☆☆)

In [4]:
v = np.zeros((10,10))
print("%d bytes" % (v.size * v.itemsize))

800 bytes


## 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


## 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 7. Create a vector with values ranging from 10 to 49

In [7]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
v = np.arange(1, 11)
print(v)
v = v[::-1]
print(v)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


## 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
v = np.arange(0, 9).reshape(3, 3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
v = np.array([1, 2, 0, 0, 4, 0])
idx = np.nonzero(v)
print(idx)

(array([0, 1, 4]),)
